
public interface Constants 
{
	public final int ENGLISH_DRAUGHT_PIECE_COUNT = 12;
	public final int ENGLISH_DRAUGHT_BOARD_SIZE = 8;
	public final int ENGLISH_DRAUGHT_BLACK_KING_HOME = 0;
	public final int ENGLISH_DRAUGHT_WHITE_KING_HOME = ENGLISH_DRAUGHT_BOARD_SIZE -1;
	public final int ENGLISH_DRAUGHT_NUMBER_OF_ROWS_FOR_PIECES = 3;
	public final int ENGLISH_DRAUGHT_WHITE_OFFSET = ENGLISH_DRAUGHT_BOARD_SIZE - ENGLISH_DRAUGHT_NUMBER_OF_ROWS_FOR_PIECES;
	public final int SCREEN_SIZE = 1000;
	public final int PIECE_SIZE = 100;
	public final int PIECE_OFFSET = SCREEN_SIZE/ENGLISH_DRAUGHT_BOARD_SIZE;
}
